const toOptions = (arr) => {
  // return arr;
  return arr.map((el) => {
    return {
      label: el,
      value: el,
    };
  });
};

const projectFields = () => {
  return {
    title: {
      label: 'Title',
    },
    kimble_engagements: {
      label: 'Kimble Engagements',
    },
    clientUnit: {
      label: 'Client Unit',
      options: ['HSBC', 'DB', 'City', 'UBS'],
    },
    country: {
      label: 'Country',
      options: ['PL', 'UK'],
    },
    startDate: {
      label: 'startDate',
      value: null,
    },
    endDate: {
      label: 'endDate',
      value: null,
    },
    status: {
      label: 'Staus',
      options: ['Open', 'Closed'],
    },
    deliveryManager: {
      label: 'Delivery Manager',
      options: ['Sample1', 'Sample2'],
    },
    projectManager: {
      label: 'Project Manager',
      options: ['Sample1', 'Sample2'],
    },
    projectHead: {
      label: 'ProjectHead',
      options: ['Sample1', 'Sample2'],
    },
    summary: {
      label: 'summary',
      value: null,
    },
    //Business Consulting
    businessConsulting: {
      competencies: {
        label: 'Competencies',
        options: toOptions([
          'Business & Functional documentation',
          'Business Analytics (data)',
          'Business Process Modelling',
          'Business Requirements Gathering / Elicitation',
          'Corporate Banking',
          'Impact Assessment',
          'Private Banking',
          'Regulation Interpretation',
          'Retail Banking',
          'Trend & Research analytics',
          'Use case modelling',
          'WealthManagement',
        ]),
      },
      coreBanking: {
        label: 'Core Banking',
        options: toOptions([
          'Agency Lending',
          'Avaloq',
          'Cards',
          'Checks',
          'Collateral Management',
          'Corporate Loans',
          'Credit & Loans',
          'CRM',
          'Deposits & Accounts',
          'Finastra Equation',
          'FIS Modern Banking platform',
          'Guarantees',
          'Islamic Banking',
          'Loans IQ',
          'Mambu',
          'Migration & Optimization',
          'Online Banking',
          'Payments',
          'Personal Loans',
          'Securitization',
          'TCS Core Banking',
          'Temenos T24',
          'Thought Machine',
        ]),
      },
      industry: {
        label: 'Industry',
        options: toOptions([
          'Digital Twins',
          'Education',
          'Enterprise Resource Planning (ERP)',
          'Healthcare',
          'Industry Accounting',
          'Industry-Engineering',
          'Industry-Finance',
          'Industry-Human Resources',
          'Industry-Logistics',
          'Industry-Management',
          'Industry-Marketing',
          'Industry-Operations',
          'Industry-Strategic planning',
          'Manufacturing Execution Systems (MES)',
          'Manufacturing-Aerospace & Defense',
          'Manufacturing-Agrofood',
          'Manufacturing-Automotive',
          'Manufacturing-Chemicals',
          'Manufacturing-Energy',
          'Manufacturing-Fast Moving Consumer Goods',
          'Manufacturing-Industrial Equipment',
          'Manufacturing-Life Sciences',
          'Manufacturing-Mining & Raw Materials',
          'Manufacturing-Pharma',
          'Media & Communication',
          'Platform economy',
          'Public services',
          'Retail',
          'Shopfloor Lean',
          'Shopfloor Management',
          'Shopfloor Six Sigma',
          'Transportation',
          'Travel & Leisure',
          'Utilities',
          'Wholesale Trade',
        ]),
      },
      insurance: {
        label: 'Insurance',
        options: toOptions([
          'Accident and Critical illness',
          'Agricultural',
          'Car',
          'Channels',
          'Claims',
          'Client management',
          'Corporate Reinsurance',
          'Fleets',
          'Guidewire',
          'Health',
          'Home',
          'Insurance Payments',
          'Life',
          'Non-Life',
          'Pricing',
          'Properties',
          'Savings and Investments',
          'Suppliers management',
          'Underwriting',
        ]),
      },
      riskLegalRegulatoryCompliance: {
        label: 'Risk, Legal, Regulatory & Compliance',
        options: toOptions([
          'Anti-Financial Crime',
          'Anti-Money Laundering',
          'Basel Accords',
          'Credit & Counterparty Risk',
          'Credit Scoring & Rating',
          'Data Protection',
          'Dodd-Frank Act',
          'DSGVO',
          'GDPR',
          'IFRS9',
          'Insurance Risk',
          'Liquidity & Assets & Liability',
          'Market Risk',
          'Market Transparency & Standardistion',
          'MIFID',
          'Model Risk',
          'Operational Risk',
          'Others APAC regulations',
          'Others LATAM Regulations',
          'Others USA Regulations',
          'Regulatory automation',
          'Regulatory Reporting Others EU Regulations',
        ]),
      },
      tradeAndAccountancy: {
        label: 'Trade and Accountancy',
        options: toOptions([
          'Balance sheet management',
          'Cash mgmt',
          'Clearing',
          'Collateral & Margin',
          'Custody and Asset Servicing',
          'Derisking',
          'Fees & commisions',
          'Financial reporting',
          'GL & SL accounting',
          'Limit Management',
          'Online Brokerage',
          'P&L Calculation/Attribution',
          'Settlements',
          'Supply Chain Finance',
          'Treasury',
        ]),
      },
    },
    // Process Automation
    processAutomation: {
      bpm: {
        label: 'BPM',
        options: toOptions([
          'Appian',
          'Appway',
          'AxxonIvy',
          'Bonita Soft',
          'Camunda',
          'Flowable',
          'IBM BPMN',
          'jBPM',
          'Tibco AMX BPM',
          'Tibco Business Works 5.X',
          'Tibco Business Works 6.X',
          'Tibco iProcess',
          'Web methods',
        ]),
      },
      cep: {
        label: 'CEP',
        options: toOptions(['Tibco Business Events']),
      },
      rpa: {
        label: 'RPA',
        options: toOptions([
          'Automate',
          'Automation anywhere',
          'Blueprism',
          'Jacada',
          'Kryon',
          'Ui Path',
        ]),
      },
    },
    //Architecture
    architecture: {
      apiGovernance: {
        label: 'API Governance',
        options: toOptions([
          'API Gateway',
          'APIS Design',
          'Oauth2',
          'RAML',
          'REST',
          'Swagger',
          'WSO2',
        ]),
      },
    },
    testing: {
      testing: {
        label: 'Testing',
        options: toOptions([
          'Functional Testing',
          'HPALM',
          'Microfocus UFT',
          'Performance Testing',
          'Security Testing',
          'Selenium',
          'Technical Testing',
          'Test Automation',
        ]),
      },
    },
    xd: {
      interactionDesign: {
        label: 'Interaction Design',
        options: toOptions([
          'Accesibility',
          'AdobeXD',
          'Axure',
          'Balsamiq',
          'Figma',
          'Flinto',
          'Framer',
          'Information Architecture',
          'Interaction Design',
          'Invision',
          'JustInMind',
          'Marvel',
          'Material Design',
          'Origami',
          'Principle',
          'Proto.Io',
          'Prototyping',
          'Sketch',
          'Usability',
          'XD Designer',
        ]),
      },
      userResearch: {
        label: 'User Research',
        options: toOptions([
          'Design Sprint',
          'Design thinking',
          'Ethno graphic research',
          'Interviews',
          'Journey Mapping',
          'Service Blueprint',
          'Surveys',
          'Testing (Usability, Guerrilla, Active, A/B)',
          'Workshop Facilitating',
        ]),
      },
      visualDesign: {
        label: 'Visual Design',
        options: toOptions([
          'Adobe Cloud',
          'Adobe Dreamweaver',
          'Brand',
          'Figma',
          'Graphic Design',
          'Illustration',
          'Sketch',
          'UI Designer',
          'Vendor Guidelines (Android, Web, iOS)',
          'Visual Design',
        ]),
      },
    },
    ai: {
      //Artificial Intelligence
      dataScience: {
        label: 'Data Science',
        options: toOptions([
          'Automation',
          'Cloud-based AI Services',
          'Computer Vision',
          'Deep Learning',
          'Keras',
          'Machine learning',
          'Natural Language Processing',
          'Pandas',
          'Python (AI-DataScience)',
          'R',
          'Rapid Miner',
          'Scala (AI-DataScience)',
          'SmartBots',
          'Spark Ml lib',
          'Tensor flow',
        ]),
      },
    },
    crm: {
      salesforce: {
        label: 'Salesforce',
        options: toOptions([
          'Apex/Trigger',
          'Cloud Craze',
          'Commerce Cloud',
          'Community Cloud',
          'CPG',
          'CPQ',
          'Einstein Analytics and Discovery',
          'Finance Cloud',
          'Governance Sandboxes',
          'Health Cloud',
          'Interface developer',
          'Lightning component (LWC)',
          'Lightning components (AURA)',
          'Sales Cloud',
          'Service Cloud',
          'SFDX - CI/CD',
          'Visualforce',
        ]),
      },
      salesforceMarketingCloud: {
        label: 'Salesforce Marketing Cloud',
        options: toOptions([
          'Automation Studio',
          'Cloud Pages',
          'Einstein - Web/Email Recommendations',
          'Email Studio',
          'Interaction Studio',
          'Journey Builder',
          'Mobile Studio',
          'Pardot',
          'Social Studio',
        ]),
      },
    },
    iot: {
      internetOfThings: {
        label: 'Internet of Things',
        options: toOptions([
          'Cloud-based IoT Services',
          'Edge computing',
          'Grafana',
          'Hardware (sensoring, devices, etc.)',
          'IoT Platforms',
          'Kibana',
          'MQTT',
          'Nifi',
        ]),
      },
    },
    ie: {
      electricalEngineering: {
        label: 'Electrical Engineering',
        options: toOptions([
          'Automation Studio',
          'Cloud Pages',
          'Einstein - Web/Email Recommendations',
          'Email Studio',
          'Interaction Studio',
          'Journey Builder',
          'Mobile Studio',
          'Pardot',
          'Social Studio',
        ]),
      },
      fieldbusSystems: {
        label: 'Fieldbus Systems',
        options: toOptions([
          'BACNet',
          'CAN-Bus',
          'EtherCAT',
          'Ethernet/IP',
          'I/O-Link',
          'Modbus RTU',
          'Modbus TCP',
          'Profibus',
          'Profinet',
          'RS232/RS485',
        ]),
      },
      industrialInternetOfThings: {
        label: 'Industrial Internet of Things',
        options: toOptions([
          'CC-Link',
          'Edge Devices',
          'MT-Connect',
          'Node-RED',
          'OPC UA',
          'Sphinx Open Online',
        ]),
      },
      pLCNC: {
        label: 'PLC / NC',
        options: toOptions([
          'ABB',
          'Allan Bradley',
          'B&R',
          'Beckhoff TC2',
          'Beckhoff TC3',
          'Fanuc',
          'Heidenhain',
          'Siemens S5',
          'Siemens S7',
          'Siemens Sinumerik',
          'Wago',
        ]),
      },
    },
    cloud: {
      ownerOfCloudService: {
        label: 'Owner of cloud service',
        options: toOptions(['GFT', 'Client', 'Third Parties']),
      },
      serviceDelivery: {
        label: 'Service delivery',
        options: toOptions([
          'Advisory',
          'PoC',
          'Software development',
          'Infrastructure support',
          'Productive operations support',
        ]),
      },
      dataProcessing: {
        label: 'Data processing',
        options: toOptions([
          'Productive client data',
          'Sensitive test data',
          'Non-sensitive test data',
          'Public data',
        ]),
      },
      amazonWebServices: {
        label: 'Amazon Web Services',
        options: toOptions([
          'Adminstration (AWS)',
          'AI (AWS)',
          'Analytics (AWS)',
          'API Gateway (AWS)',
          'BigData (AWS)',
          'Cloud Formation (AWS)',
          'Compute (AWS)',
          'Database (AWS)',
          'DevOps Tools (AWS)',
          'DLT(AWS)',
          'Elastic Kubernetes Service (AWS)',
          'IoT Services (AWS)',
          'Machine Learning (AWS)',
          'Migration (AWS)',
          'Monitoring (AWS)',
          'Networking (AWS)',
          'Security(AWS)',
          'Serverless (AWS)',
          'Storage (AWS)',
          'Virtualization (AWS)',
        ]),
      },
      cloudOps: {
        label: 'CloudOps',
        options: toOptions([
          'Ansible (CloudOps)',
          'App Insights (CloudOps)',
          'ARM',
          'Bash (CloudOps)',
          'Chef',
          'Cloud cost management (CloudOps)',
          'CloudFormation',
          'CloudWatch',
          'Google Deployment Manager',
          'Infrastructure as Code (CloudOps)',
          'Log Analytics (CloudOps)',
          'Monitoring (CloudOps)',
          'Puppet (CloudOps)',
          'Python (CloudOps)',
          'Shell scripting (CloudOps)',
          'StackDriver (CloudOps)',
          'Terraform (CloudOps)',
          'Vagrant (CloudOps)',
          'VPC administration',
        ]),
      },
      googleCloudPlatform: {
        label: 'Google Cloud Platform',
        options: toOptions([
          'Adminstration (Google)',
          'AI (Google)',
          'Analytics (Google)',
          'Anthos',
          'API Management',
          'BigData (Google)',
          'BigQuery (Google)',
          'BigTable (Google)',
          'Cloud Build',
          'Cloud Endpoints (Google)',
          'Compute (Google)',
          'Database (Google)',
          'DLT (Google)',
          'Google Deployment Manager',
          'Google Kubernetes Engine',
          'IoT (Google)',
          'Machine Learning (Google)',
          'Migration (Google)',
          'Monitoring (Google)',
          'Networking (Google)',
          'Security (Google)',
          'Serverless (Google)',
          'Storage (Google)',
          'Virtualization (Google)',
        ]),
      },
      microsoftAzure: {
        label: 'Microsoft Azure',
        options: toOptions([
          'Adminstration (Azure)',
          'AI (Azure)',
          'Analytics (Azure)',
          'API Management (Azure)',
          'Azure Arc',
          'Azure DevOps',
          'Azure Kubernetes Service',
          'Azure Resource Manager',
          'BigData (Azure)',
          'Compute (Azure)',
          'Database (Azure)',
          'DLT (Azure)',
          'IoT Services (Azure)',
          'Machine Learning (Azure)',
          'Migration (Azure)',
          'Monitoring (Azure)',
          'Networking (Azure)',
          'Security (Azure)',
          'Serverless (Azure)',
          'Storage (Azure)',
          'Virtualization (Azure)',
        ]),
      },
      others: {
        label: 'Others',
        options: toOptions(['Alibaba Cloud', 'CloudFoundry', 'Oracle Cloud']),
      },
    },
    backend: {
      highPerformance: {
        label: ' High Performance',
        options: toOptions([
          'Akka',
          'Java 8+',
          'Lagom',
          'Scala (Backend-HighPerformance)',
          'Streaming',
        ]),
      },
      middleware: {
        label: ' Middleware',
        options: toOptions([
          'Apache Camel',
          'ESBs',
          'GraphQL',
          'Ibatis',
          'JBoss',
          'Message Brokers',
          'Servlet Container',
          'Spring Integration',
          'Weblogic',
          'Websphere',
        ]),
      },
      scriptingLanguages: {
        label: ' Scripting Languages',
        options: toOptions(['Perl']),
      },
      services: {
        label: ' Services',
        options: toOptions([
          'Business Rules Engine',
          'C',
          'C++',
          'DL1',
          'EJB',
          'Express',
          'Go',
          'Gosu',
          'Groovy',
          'Guidewire BE',
          'Hibernate',
          'J2EE',
          'Java',
          'JMS',
          'JPA',
          'JSF',
          'JSP',
          'Keycloak',
          'Kotlin (Backend-Services)',
          'Micronaut',
          'Microservices',
          'NestJS',
          'Next.js',
          'nodeJS(Backend-Services)',
          'Pascal',
          'PHP',
          'Python(Backend-Services)',
          'Quarkus',
          'REST',
          'Ruby',
          'Rust',
          'SOAP WebServices',
          'Spring',
          'SpringBoot',
          'SpringCloud',
          'Struts',
        ]),
      },
      unitTesting: {
        label: ' Unit Testing',
        options: toOptions(['EasyMock', 'JUnit', 'Mockito', 'PowerMock']),
      },
    },
    devOps: {
      automatedTesting: {
        label: ' Automated Testing',
        options: toOptions([
          'Backup & Monitoring',
          'Behaviour Driven Development',
          'Mobile Application Testing',
          'Performance Testing',
          'Security Testing',
          'Test Driven Development',
          'Testingin Cloud',
          'Web Application Testing',
        ]),
      },
      continuousDelivery: {
        label: ' Continuous Delivery',
        options: toOptions([
          'Chatbots',
          'Database deployment',
          'ElasticSearch (Continuous Delivery)',
          'Log aggregation',
          'Log visualization',
          'Monitoring Tools',
          'Release Management',
        ]),
      },
      infrastructureAsCode: {
        label: ' Infrastructure as Code',
        options: toOptions([
          'Ansible (Infrastructure as code)',
          'AWS Cli',
          'Azure CLI',
          'Chef (Infrastructure as code)',
          'CloudFormation',
          'IaC in Cloud',
          'IaC on premise',
          'Openstack',
          'Packer (Infrastructure as code)',
          'Puppet (Infrastructure as code)',
          'Shell Scripting (Infrastructure as code)',
          'Terraform (Infrastructure as code)',
          'Vagrant (Infrastructure as code)',
        ]),
      },
      sDLC: {
        label: ' SDLC',
        options: toOptions([
          'Artifact repositories',
          'Azure DevOps',
          'Branching strategies',
          'Build Tools',
          'Continuous integration servers',
          'Git',
          'Jenkins',
          'Maven',
          'Sonar',
          'Source code quality tools',
          'Source code repositories',
          'Task Tracking system',
          'TeamCity',
          'Vault',
        ]),
      },
      sysOps: {
        label: ' SysOps',
        options: toOptions([
          'Ansible (SysOps)',
          'Application Server (SysOps)',
          'Automated configuration management',
          'Bash (SysOps)',
          'Chef (SysOps)',
          'Citrix',
          'Clustering / Application Distribution',
          'Container Management (SysOps)',
          'Docker (SysOps)',
          'Elasticsearch (SysOps)',
          'Grafana (SysOps)',
          'Haproxy',
          'HyperV',
          'Infrastructure as Code (SysOps)',
          'Istio',
          'Kibana (SysOps)',
          'Kubernetes (SysOps)',
          'Linux',
          'Load Balancer',
          'Monitoring (SysOps)',
          'Network administration (SysOps)',
          'Nomad',
          'Openshift (SysOps)',
          'Operating system administration',
          'OS and Network Security',
          'Prometheus (SysOps)',
          'Puppet (SysOps)',
          'Python (SysOps)',
          'Release Manager (SysOps)',
          'Server Administration (SysOps)',
          'Service Manager (SysOps)',
          'Services Mesh',
          'Shell scripting (SysOps)',
          'System Administrator (SysOps)',
          'Vagrant (SysOps)',
          'VirtualBox',
          'VMWare',
          'Web Servers',
          'Windows',
        ]),
      },
    },

    data: {
      bI: {
        label: ' BI',
        options: toOptions([
          'Business Intelligence',
          'Cognos',
          'Data Mart',
          'Data Mining',
          'Data Virtualization',
          'Data Visualization',
          'DataWarehouse',
          'Enterprise Content Management',
          'Microstrategy',
          'MS Reporting Services',
          'PowerBI',
          'QlikSense',
          'QlikView',
          'Reporting',
          'SAP BO',
          'SAS',
          'Tableau',
        ]),
      },
      bigDataStreaming: {
        label: ' BigData  Streaming',
        options: toOptions([
          'Apache Beam',
          'Apache Lucene',
          'Cassandra',
          'ElasticSearch (BigData-Streaming)',
          'Flink',
          'Flume',
          'Hadoop',
          'Hive',
          'Kafka',
          'MapReduce',
          'NoSQL',
          'Spark',
        ]),
      },
      cache: {
        label: ' Cache',
        options: toOptions(['Coherence', 'Hazelcast']),
      },
      dataAnalysisAndModelling: {
        label: ' Data Analysis and Modelling',
        options: toOptions([
          'Data Analysis (Business and functional Design)',
          'Data Architecture',
          'Data Governance',
          'Data Modelling (Erwin,PowerDesigner)',
          'Data Standards',
          'Data Strategy',
          'Data analysis',
          'Data Architecture',
          'Data Governance',
          'Data Integration & ETL',
          'Data Lineage',
          'Data modelling',
          'Data Quality',
          'Data standards',
          'Data Strategy',
          'Denodo',
          'Dremio',
          'Erwin',
          'Informatica PowerCenter',
          'Pentaho',
          'Power designer',
        ]),
      },
      database: {
        label: ' Database',
        options: toOptions([
          'Apache Impala',
          'Data base administration(DBA)',
          'DB2',
          'In-Memory database',
          'MongoDB',
          'mySQL',
          'Oracle',
          'PL/SQL',
          'PostgreSQL',
          'Relational databases(Others)',
          'SQLServer',
          'Sybase',
          'Teradata',
          'Zookeeper',
        ]),
      },
    },
    mainframe: {
      development: {
        label: ' Development',
        options: toOptions([
          'Cics',
          'Cobol',
          'DB2',
          'Host',
          'JCL',
          'Microfocus Enterprise Developer',
          'PL/1',
          'TP Mainframe',
        ]),
      },
      problemDetermination: {
        label: ' Problem Determination',
        options: toOptions([
          'Debugger',
          'Dump Analysis',
          'File Manager',
          'Performance Analysis',
          'Rexx',
        ]),
      },
    },

    environment: {
      development: {
        label: ' Development',
        options: toOptions(['Eclipse', 'IntelliJ', 'Other IDE']),
      },
    },

    frontEnd: {
      frontend: {
        label: ' Frontend',
        options: toOptions([
          'Ajax',
          'Angular',
          'Angular JS',
          'Bootstrap',
          'CSS3',
          'Electron',
          'Ember',
          'ES6',
          'Gatsby.js',
          'Guidewire FE',
          'Guidewire Portals',
          'GWT',
          'HTML5',
          'Ionic',
          'JavaScript',
          'JQuery',
          'Layout',
          'MobX',
          'Node.js(Frontend)',
          'Polymer',
          'React',
          'Redux',
          'Svelte',
          'TypeScript',
          'Vue.js',
          'Websockets',
        ]),
      },
      lowCode: {
        label: ' LowCode',
        options: toOptions([
          'Microsoft Power Apps',
          'OutSystems',
          'PegaSystems',
        ]),
      },
      unitTesting: {
        label: ' Unit Testing',
        options: toOptions([
          'Chai.js',
          'Cypress',
          'Enzyme',
          'Jasmine',
          'Jest',
          'Karma',
          'Mocha',
          'Puppeteer',
          'Sinon.JS',
        ]),
      },
    },

    dlt: {
      blockchain: {
        label: ' Blockchain',
        options: toOptions([
          'Corda',
          'DAML',
          'Ethereum',
          'Hyperledger',
          'IOTA',
          'Quorum',
        ]),
      },
    },

    microsoft: {
      microsoft: {
        label: ' Microsoft',
        options: toOptions([
          '.Net',
          '.NETCore',
          'ASP.NET',
          'C#',
          'Entity Framework',
          'Sharepoint Development',
          'SQLServer',
          'VB.net',
          'Visual Basic',
          'Visual Designer',
          'WPF',
        ]),
      },
    },

    mobile: {
      hybrid: {
        label: ' Hybrid',
        options: toOptions([
          'Cordova',
          'Flutter Framework',
          'Frontend Skills',
          'Ionic',
          'Plugin Development',
          'Xamarin',
        ]),
      },
      native: {
        label: ' Native',
        options: toOptions([
          'Android C++',
          'Android Java',
          'Dart',
          'iOS Objective-C',
          'iOS Swift',
          'Kotlin (Mobile-Native)',
          'Native Script',
          'React Native',
        ]),
      },
    },
  };
};

export { projectFields };
